/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: "native" | "wasm32-wasi" | "wasm32-wasip1";

export interface AnimationDataDto {
  fps: number;
  baseFrame: number;
  frames: Array<Array<number>>;
  validity: Array<boolean>;
  skeleton: Array<SkeletonBoneDto>;
  rootX: number;
  rootY: number;
}

export interface AnimConfigDto {
  fps: number;
  baseFrame: number;
  propagate: boolean;
}

export interface BoneFrameDto {
  rotations: Array<number>;
  confidence: number;
  valid: boolean;
}

export declare function buildAnimation(
  bones: Array<BoneFrameDto>,
  frames: Array<Array<Pose2DDto>>,
  config: AnimConfigDto,
  rigConfig: RigConfigDto,
  imageHeight: number,
): AnimationDataDto;

export declare function buildAtlas(
  layout: PackLayoutDto,
  imageName: string,
  filter: string,
  repeat: string,
): string;

export declare function buildSpineJson(
  animation: AnimationDataDto,
  config: ExportConfigDto,
): string;

export interface DecodeConfigDto {
  confidenceThreshold: number;
  nmsRadius: number;
  maxPoses: number;
  stride: number;
  multiPose: boolean;
  /** `"nhwc"` 或 `"nchw"`。 */
  heatmapLayout: string;
  offsetLayout: string;
  /** `"yx"` 或 `"xy"`。 */
  offsetOrder: string;
  displacementLayout: string;
  offsetInPixels: boolean;
}

export declare function decodePoses(
  heatmaps: Float32Array,
  offsets: Float32Array,
  displacementsFwd: Float32Array,
  displacementsBwd: Float32Array,
  heatmapWidth: number,
  heatmapHeight: number,
  numParts: number,
  config: DecodeConfigDto,
  transform: ImageTransformDto,
): Array<Pose2DDto>;

export declare function decodeRegression(
  values: Float32Array,
  numParts: number,
  modelWidth: number,
  modelHeight: number,
  transform: ImageTransformDto,
): Pose2DDto;

export interface ExportConfigDto {
  name: string;
  animationName: string;
  frameWidth: number;
  frameHeight: number;
  frameCount: number;
  fps: number;
  regionPrefix: string;
  imageName: string;
  imageScale: number;
}

export interface ImageTransformDto {
  scale: number;
  offsetX: number;
  offsetY: number;
}

export interface KeypointDto {
  x: number;
  y: number;
  score: number;
}

export declare function keypointNames(): Array<string>;

export declare function letterboxTransformFor(
  srcWidth: number,
  srcHeight: number,
  dstWidth: number,
  dstHeight: number,
): ImageTransformDto;

export interface PackConfigDto {
  maxWidth: number;
  padding: number;
  scale: number;
}

export interface PackedRegionDto {
  name: string;
  x: number;
  y: number;
  width: number;
  height: number;
  index: number;
}

export declare function packFrames(
  frameWidth: number,
  frameHeight: number,
  count: number,
  config: PackConfigDto,
): PackLayoutDto;

export interface PackLayoutDto {
  atlasWidth: number;
  atlasHeight: number;
  regions: Array<PackedRegionDto>;
}

export interface Pose2DDto {
  score: number;
  keypoints: Array<KeypointDto>;
}

export declare function posesToBones(
  frames: Array<Array<Pose2DDto>>,
  config: RigConfigDto,
  imageHeight: number,
): Array<BoneFrameDto>;

export declare function preprocess(
  rgba: Uint8Array,
  srcWidth: number,
  srcHeight: number,
  dstWidth: number,
  dstHeight: number,
  mean: Array<number>,
  scale: number,
  flipX: boolean,
): Float32Array;

export declare function preprocessLetterbox(
  rgba: Uint8Array,
  srcWidth: number,
  srcHeight: number,
  dstWidth: number,
  dstHeight: number,
  flipX: boolean,
): Int32Array;

export interface RigConfigDto {
  minConfidentKeypoints: number;
  confidenceThreshold: number;
}

export interface SkeletonBoneDto {
  name: string;
  parent?: string;
  length: number;
  x: number;
  y: number;
  rotation: number;
}

export declare function smoothAngleSeries(values: Float32Array, bufferSize: number): Float32Array;

export interface SmoothConfigDto {
  bufferSize: number;
  confidenceThreshold: number;
}

export declare function smoothPoses(
  frames: Array<Array<Pose2DDto>>,
  config: SmoothConfigDto,
): Array<Array<Pose2DDto>>;

/** 导出的 Spine JSON 声明的格式版本（与 WASM 侧、与 `spine::SPINE_VERSION` 同源）。 */
export declare function spineVersion(): string;

export declare function transformFor(
  srcWidth: number,
  srcHeight: number,
  dstWidth: number,
  dstHeight: number,
): ImageTransformDto;

export declare function version(): string;
